bind 0.0.0.0
protected-mode yes
port 6379
dir /data

# Persistence
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
save 900 1
save 300 10
save 60 10000

# Capacity controls
maxmemory 3gb
maxmemory-policy allkeys-lru
tcp-keepalive 300
notify-keyspace-events Ex

loglevel notice
