from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class AgentDefinition:
    index: int
    agent_id: str
    short_code: str
    name: str
    tier: str
    pod: str
    role: str
    category: str
    specialties: tuple[str, ...] = ()
    runtime_class: str = "synthesized_heartbeat"

    @property
    def pod_assignment(self) -> str:
        """Audit-facing alias for the registry pod assignment."""
        return self.pod

    @property
    def language_keys(self) -> tuple[str, ...]:
        """Audit-facing alias for specialist language keys."""
        return self.specialties
    # Derived in __post_init__ — callers should not set this directly.
    # runtime_class values:
    #   "shared_worker"         — runs inside a shared pod-worker container
    #                             (categories: specialist, pod_manager, pod_audit)
    #   "synthesized_heartbeat" — no real container; heartbeat generated by orchestrator
    #                             (categories: interface, executive, support)

    def __post_init__(self) -> None:
        # Derive runtime_class from category when the default placeholder is still set.
        # Using object.__setattr__ because the dataclass is frozen.
        if self.category in {"specialist", "pod_manager", "pod_audit"}:
            object.__setattr__(self, "runtime_class", "shared_worker")


AGENT_REGISTRY: Final[tuple[AgentDefinition, ...]] = (
    AgentDefinition(
        index=1,
        agent_id="AGENT-01-PM",
        short_code="PM",
        name="PM Agent",
        tier="User Interface",
        pod="User Interface",
        role="Program manager and mission intake translation",
        category="interface",
    ),
    AgentDefinition(
        index=2,
        agent_id="AGENT-02-CEO",
        short_code="CEO",
        name="CEO Agent",
        tier="Executive",
        pod="Executive",
        role="Cross-pod orchestration and global state ownership",
        category="executive",
    ),
    AgentDefinition(
        index=3,
        agent_id="AGENT-03-BROKER",
        short_code="BROKER",
        name="API Broker",
        tier="Support Ring",
        pod="Support Ring",
        role="API routing, key management, and rate-limit control",
        category="support",
    ),
    AgentDefinition(
        index=4,
        agent_id="AGENT-04-ACCOUNTANT",
        short_code="ACCOUNTANT",
        name="Accountant",
        tier="Support Ring",
        pod="Support Ring",
        role="Token-cost monitoring and budget enforcement",
        category="support",
    ),
    AgentDefinition(
        index=5,
        agent_id="AGENT-05-SECURITY",
        short_code="SECURITY",
        name="Security Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="Security scanning and threat detection",
        category="support",
    ),
    AgentDefinition(
        index=6,
        agent_id="AGENT-06-IS",
        short_code="IS",
        name="IS Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="Knowledge indexing and standards updates",
        category="support",
    ),
    AgentDefinition(
        index=7,
        agent_id="AGENT-07-VC",
        short_code="VC",
        name="Version Control Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="Commit strategy, rollback, and provenance traceability",
        category="support",
    ),
    AgentDefinition(
        index=8,
        agent_id="AGENT-08-COMPLIANCE",
        short_code="COMPLIANCE",
        name="Compliance Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="License compatibility and legal provenance checks",
        category="support",
    ),
    AgentDefinition(
        index=9,
        agent_id="AGENT-09-HW",
        short_code="HW",
        name="Hardware-Mapping Injector",
        tier="Support Ring",
        pod="Support Ring",
        # Reserved role. Binary synthesis was formally retired on 2026-08-01
        # (ADR_DESIGN_RECONCILIATION_2026-08-01.md, D2), so this agent carries no
        # compilation or hardware-mapping responsibility; it exists to supply
        # target-profile hints to generation if that path is ever activated.
        role="Reserved: target-profile hints for generation (no compilation role)",
        category="support",
    ),
    AgentDefinition(
        index=10,
        agent_id="AGENT-10-TESTER",
        short_code="TESTER",
        name="System Integration Tester",
        tier="Support Ring",
        pod="Support Ring",
        role="End-to-end validation and performance benchmarking",
        category="support",
    ),
    AgentDefinition(
        index=11,
        agent_id="AGENT-11-DEPLOY",
        short_code="DEPLOY",
        name="Deployment Agent",
        tier="Support Ring",
        pod="Support Ring",
        # "Binary packaging" until 2026-08-01. theFactory delivers source
        # artifacts and gzipped bundles, never compiled binaries — see
        # ADR_DESIGN_RECONCILIATION_2026-08-01.md, D2.
        role="Artifact packaging, delivery, and environment setup",
        category="support",
    ),
    AgentDefinition(
        index=12,
        agent_id="AGENT-12-PODA-MGR",
        short_code="PODA-MGR",
        name="Pod A Sub-Manager",
        tier="Refinement Pod",
        pod="Pod A",
        role="Coordinate dynamic-language extraction and fusion in Pod A",
        category="pod_manager",
    ),
    AgentDefinition(
        index=13,
        agent_id="AGENT-13-PODA-AUDIT",
        short_code="PODA-AUDIT",
        name="Pod A QC/Audit",
        tier="Refinement Pod",
        pod="Pod A",
        role="Verify Pod A LogicNodes before pod-level release",
        category="pod_audit",
    ),
    AgentDefinition(
        index=14,
        agent_id="AGENT-14-PYTHON",
        short_code="PYTHON",
        name="Python Specialist",
        tier="Refinement Pod",
        pod="Pod A",
        role="Extract computational intent from Python workloads",
        category="specialist",
        specialties=("python",),
    ),
    AgentDefinition(
        index=15,
        agent_id="AGENT-15-JAVASCRIPT",
        short_code="JAVASCRIPT",
        name="JavaScript Specialist",
        tier="Refinement Pod",
        pod="Pod A",
        role="Extract computational intent from JavaScript/TypeScript workloads",
        category="specialist",
        specialties=("javascript",),
    ),
    AgentDefinition(
        index=16,
        agent_id="AGENT-16-RUBY",
        short_code="RUBY",
        name="Ruby Specialist",
        tier="Refinement Pod",
        pod="Pod A",
        role="Extract computational intent from Ruby workloads",
        category="specialist",
        specialties=("ruby",),
    ),
    AgentDefinition(
        index=17,
        agent_id="AGENT-17-PHP",
        short_code="PHP",
        name="PHP Specialist",
        tier="Refinement Pod",
        pod="Pod A",
        role="Extract computational intent from PHP workloads",
        category="specialist",
        specialties=("php",),
    ),
    AgentDefinition(
        index=18,
        agent_id="AGENT-18-PODB-MGR",
        short_code="PODB-MGR",
        name="Pod B Sub-Manager",
        tier="Refinement Pod",
        pod="Pod B",
        role="Coordinate systems-language extraction and fusion in Pod B",
        category="pod_manager",
    ),
    AgentDefinition(
        index=19,
        agent_id="AGENT-19-PODB-AUDIT",
        short_code="PODB-AUDIT",
        name="Pod B QC/Audit",
        tier="Refinement Pod",
        pod="Pod B",
        role="Verify Pod B LogicNodes before pod-level release",
        category="pod_audit",
    ),
    AgentDefinition(
        index=20,
        agent_id="AGENT-20-C",
        short_code="C",
        name="C Specialist",
        tier="Refinement Pod",
        pod="Pod B",
        role="Extract computational intent from C workloads",
        category="specialist",
        specialties=("c",),
    ),
    AgentDefinition(
        index=21,
        agent_id="AGENT-21-CPP",
        short_code="CPP",
        name="C++ Specialist",
        tier="Refinement Pod",
        pod="Pod B",
        role="Extract computational intent from C++ workloads",
        category="specialist",
        specialties=("cpp",),
    ),
    AgentDefinition(
        index=22,
        agent_id="AGENT-22-RUST",
        short_code="RUST",
        name="Rust Specialist",
        tier="Refinement Pod",
        pod="Pod B",
        role="Extract computational intent from Rust workloads",
        category="specialist",
        specialties=("rust",),
    ),
    AgentDefinition(
        index=23,
        agent_id="AGENT-23-ZIG",
        short_code="ZIG",
        name="Zig Specialist",
        tier="Refinement Pod",
        pod="Pod B",
        role="Extract computational intent from Zig workloads",
        category="specialist",
        specialties=("zig",),
    ),
    AgentDefinition(
        index=24,
        agent_id="AGENT-24-PODC-MGR",
        short_code="PODC-MGR",
        name="Pod C Sub-Manager",
        tier="Refinement Pod",
        pod="Pod C",
        role="Coordinate enterprise-language extraction and fusion in Pod C",
        category="pod_manager",
    ),
    AgentDefinition(
        index=25,
        agent_id="AGENT-25-PODC-AUDIT",
        short_code="PODC-AUDIT",
        name="Pod C QC/Audit",
        tier="Refinement Pod",
        pod="Pod C",
        role="Verify Pod C LogicNodes before pod-level release",
        category="pod_audit",
    ),
    AgentDefinition(
        index=26,
        agent_id="AGENT-26-JAVA",
        short_code="JAVA",
        name="Java Specialist",
        tier="Refinement Pod",
        pod="Pod C",
        role="Extract computational intent from Java workloads",
        category="specialist",
        specialties=("java",),
    ),
    AgentDefinition(
        index=27,
        agent_id="AGENT-27-CSHARP",
        short_code="CSHARP",
        name="C# Specialist",
        tier="Refinement Pod",
        pod="Pod C",
        role="Extract computational intent from C# workloads",
        category="specialist",
        specialties=("csharp",),
    ),
    AgentDefinition(
        index=28,
        agent_id="AGENT-28-SCALA",
        short_code="SCALA",
        name="Scala Specialist",
        tier="Refinement Pod",
        pod="Pod C",
        role="Extract computational intent from Scala workloads",
        category="specialist",
        specialties=("scala",),
    ),
    AgentDefinition(
        index=29,
        agent_id="AGENT-29-KOTLIN",
        short_code="KOTLIN",
        name="Kotlin Specialist",
        tier="Refinement Pod",
        pod="Pod C",
        role="Extract computational intent from Kotlin workloads",
        category="specialist",
        specialties=("kotlin",),
    ),
    AgentDefinition(
        index=30,
        agent_id="AGENT-30-PODD-MGR",
        short_code="PODD-MGR",
        name="Pod D Sub-Manager",
        tier="Refinement Pod",
        pod="Pod D",
        # "mathematical-language" until 2026-08-01. Pod D also holds Haskell and
        # OCaml, which are functional rather than mathematical (UPG-23). The
        # pod key "Pod D" is a routing identifier and deliberately unchanged.
        role="Coordinate mathematical and functional language extraction and fusion in Pod D",
        category="pod_manager",
    ),
    AgentDefinition(
        index=31,
        agent_id="AGENT-31-PODD-AUDIT",
        short_code="PODD-AUDIT",
        name="Pod D QC/Audit",
        tier="Refinement Pod",
        pod="Pod D",
        role="Verify Pod D LogicNodes before pod-level release",
        category="pod_audit",
    ),
    AgentDefinition(
        index=32,
        agent_id="AGENT-32-MATLAB",
        short_code="MATLAB",
        name="MATLAB Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from MATLAB workloads",
        category="specialist",
        specialties=("matlab",),
    ),
    AgentDefinition(
        index=33,
        agent_id="AGENT-33-R",
        short_code="R",
        name="R Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from R workloads",
        category="specialist",
        specialties=("r",),
    ),
    AgentDefinition(
        index=34,
        agent_id="AGENT-34-JULIA",
        short_code="JULIA",
        name="Julia Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from Julia workloads",
        category="specialist",
        specialties=("julia",),
    ),
    AgentDefinition(
        index=35,
        agent_id="AGENT-35-MATHEMATICA",
        short_code="MATHEMATICA",
        name="Mathematica Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from Mathematica workloads",
        category="specialist",
        specialties=("mathematica",),
    ),
    AgentDefinition(
        index=36,
        agent_id="AGENT-36-GO",
        short_code="GO",
        name="Go Specialist",
        tier="Refinement Pod",
        pod="Pod B",
        role="Extract computational intent from Go workloads",
        category="specialist",
        specialties=("go",),
    ),
    AgentDefinition(
        index=37,
        agent_id="AGENT-37-HASKELL",
        short_code="HASKELL",
        name="Haskell Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from Haskell workloads",
        category="specialist",
        specialties=("haskell",),
    ),
    AgentDefinition(
        index=38,
        agent_id="AGENT-38-OCAML",
        short_code="OCAML",
        name="OCaml Specialist",
        tier="Refinement Pod",
        pod="Pod D",
        role="Extract computational intent from OCaml workloads",
        category="specialist",
        specialties=("ocaml",),
    ),
    # Factory Capability Expansion — Phase 1
    AgentDefinition(
        index=39,
        agent_id="AGENT-39-DEPABS",
        short_code="DEPABS",
        name="Dependency Absorption Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="Dependency absorption: intent extraction, equivalence planning, and SBOM delta",
        category="support",
    ),
    AgentDefinition(
        index=40,
        agent_id="AGENT-40-TESTDATA",
        short_code="TESTDATA",
        name="Database and Test Data Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="Ephemeral test environment provisioning, schema setup, and synthetic data generation",
        category="support",
    ),
    AgentDefinition(
        index=41,
        agent_id="AGENT-41-RQCA",
        short_code="RQCA",
        name="Runtime QC Agent",
        tier="Support Ring",
        pod="Support Ring",
        role="AI-driven browser and CLI runtime quality control in ephemeral sandbox environments",
        category="support",
    ),
)


LANGUAGE_ALIASES: Final[dict[str, str]] = {
    "js": "javascript",
    "javascript": "javascript",
    "typescript": "javascript",
    "ts": "javascript",
    "py": "python",
    "python": "python",
    "rb": "ruby",
    "ruby": "ruby",
    "php": "php",
    "go": "go",
    "golang": "go",
    "c": "c",
    "c++": "cpp",
    "cpp": "cpp",
    "cc": "cpp",
    "rust": "rust",
    "zig": "zig",
    "java": "java",
    "c#": "csharp",
    "csharp": "csharp",
    "scala": "scala",
    "kotlin": "kotlin",
    "matlab": "matlab",
    "r": "r",
    "julia": "julia",
    "mathematica": "mathematica",
    "haskell": "haskell",
    "hs": "haskell",
    "ocaml": "ocaml",
    "ml": "ocaml",
}


def normalize_language(value: str | None) -> str:
    if not value:
        return ""
    normalized = value.strip().lower()
    normalized = normalized.replace(" ", "")
    return LANGUAGE_ALIASES.get(normalized, normalized)
